---
title: Afterthoughts
timezone: UTC
collections:
  category-1:
    title: Category 1
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Cuillin95@gmail.com
description: 'A place for miscellaneous writing and thoughts

'
logo: "/assets/images/logo.jpg"
baseurl: ''
url: https://notcuillin.github.io
paginate: 5
name: Cuillin
bio: 'Writer studying at UT Austin

'
author_image: "/assets/images/author.jpg"
twitter_username: notcuillin
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
- jekyll-paginate
