---
title: Afterthoughts
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Cuillin95@gmail.com
description: A place for miscellaneous writing and thoughts
logo: "/assets/images/logo.jpg"
baseurl: 
url: https://notcuillin.github.io
paginate: 5
name: Cuillin
bio: A place for miscellaneous writing and thoughts
author_image: "/assets/images/author.jpg"
twitter_username: notcuillin
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
- jekyll-paginate
webserver_headers:
  Access-Control-Allow-Origin: "*"
