<<<<<<< HEAD
# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
=======
---
>>>>>>> origin/master
title: Afterthoughts
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Cuillin95@gmail.com
<<<<<<< HEAD
description: >
  A place for miscellaneous writing and thoughts
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://notcuillin.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Cuillin'
bio: >
  Writer studying at UT Austin
author_image: "/assets/images/author.jpg"
twitter_username: notcuillin
=======
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
>>>>>>> origin/master

'
baseurl: ''
url: https://notcuillin.github.io
twitter_username: notCuillin
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
